resources:
  repositories:
    - repository: templates
      type: github
      name: Tereius/conan-azure-templates
      ref: dev
      endpoint: Tereius

jobs:
  - job: Upload
    condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - template: uploadConanRecipe.yml@templates
        parameters:
          conanEnv:
            {
              CONAN_UPLOAD: "https://conan.privatehive.de/artifactory/api/conan/public-conan",
              CONAN_LOGIN_USERNAME: "ci",
              CONAN_PASSWORD: "$(secret)",
            }
